import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderComponent from "@/components/HeaderComponent";
import About from "@/components/About";

import { Inter as FontSans } from "next/font/google";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { cn } from "@/lib/utils";
import Services from "@/components/Services";
import Project from "@/components/Project";
import Resume from "@/components/Resume";
import Contact from "@/components/Contact";
import { ThemeProvider } from "@/components/theme-provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={cn(
          "min-h-screen   font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="sticky top-0">
            <HeaderComponent />
          </div>
          {children}
          <About />
          <Services />
          <Project />
          <Resume />
          <Contact />
        </ThemeProvider>
      </body>
    </html>
  );
}
